### ISSUE TITLE
建议收集

### ISSUE THREAD

**Issue by lin2j** [lin2j/easy-deploy#2]
有任何建议都可以在这里提出，我会认真阅读。如果有新的功能希望加入到插件中，**可以提一个新的 issue，描述清楚希望实现的效果。**

**Comment by lin2j** [comment]
> ![image](https://user-images.githubusercontent.com/48015924/215725969-730a406e-f0ff-425d-b317-f5fe31a1e027.png)
> 这边`取消`单词拼错了呢

谢谢，之前没注意，会尽快更新

**Comment by JoeyWu123** [comment]
你好，感谢你的这个项目
我用这个插件可以成功连接Vultr服务器，但是无法连接我的树莓派(最新的Debian bullseye 系统）
以下是找到的报错信息，好像是加密算法不匹配的问题
java.io.IOException: There was a problem while connecting to 192.168.1.9:22
	at ch.ethz.ssh2.Connection.connect(Connection.java:699)
	at ch.ethz.ssh2.Connection.connect(Connection.java:490)
	at tech.lin2j.idea.plugin.service.SshService.getConnection(SshService.java:43)
	at tech.lin2j.idea.plugin.service.SshService.isValid(SshService.java:161)
	at tech.lin2j.idea.plugin.ui.HostUi$TestActionListener$1.run(HostUi.java:158)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
	at ch.ethz.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:91)
	at ch.ethz.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:229)
	at ch.ethz.ssh2.Connection.connect(Connection.java:655)
	... 24 more
Caused by: java.io.IOException: Cannot negotiate, proposals do not match.
	at ch.ethz.ssh2.transport.KexManager.handleMessage(KexManager.java:412)
	at ch.ethz.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:753)
	at ch.ethz.ssh2.transport.TransportManager$1.run(TransportManager.java:468)
	... 1 more
再次感谢

**Comment by toohandsome** [comment]
command 增加 上传文件名 变量

**Comment by lin2j** [comment]
> command 增加 上传文件名 变量

你是希望通过 Command 上传脚本吗？

**Comment by toohandsome** [comment]
> > command 增加 上传文件名 变量
> 
> 你是希望通过 Command 上传脚本吗？

我希望在脚本里面提供一个 我当前选择的上传文件的文件名的变量

比如
mv {selectedFile}  /opt/newFile

**Comment by morhaimi** [comment]
能否支持文件夹功能，可以将添加的连接分在不通文件夹里，方便管理

**Comment by lin2j** [comment]
> 能否支持文件夹功能，可以将添加的连接分在不通文件夹里，方便管理

你是希望能将服务器的连接信息进行分组，然后可以只看某一组的信息吗？

**Comment by morhaimi** [comment]
> > 能否支持文件夹功能，可以将添加的连接分在不通文件夹里，方便管理
> 
> 你是希望能将服务器的连接信息进行分组，然后可以只看某一组的信息吗？
是的

**Comment by morhaimi** [comment]
> > 能否支持文件夹功能，可以将添加的连接分在不通文件夹里，方便管理
> 
> 你是希望能将服务器的连接信息进行分组，然后可以只看某一组的信息吗？
>
是的

**Comment by klaus-cicd** [comment]
你好，能否支持Alibaba Cloud Toolkit的 maven package，否则现状就是在做上传之前需要手动去执行mvn package，感谢。

**Comment by lin2j** [comment]
> 你好，能否支持Alibaba Cloud Toolkit的 maven package，否则现状就是在做上传之前需要手动去执行mvn package，感谢。

一个挺方便的功能，我研究一下怎么实现，后面加进去。

**Comment by superrongzzz** [comment]
您好，能否支持通配符的方式进行上传文件和执行脚本，这样只要对于同一个项目，上传文件的时候可以忽略版本号，否则每次更新版本都要修改，另外执行的脚本可以进行统一，不用每个项目都单独写，我举例说明：

**1. 上传文件**
目前正在开发着  user-1.0.0-SNAPSHOT.jar 和 account-1.1.0-SNAPSHOT.jar两个项目
在上传文件那里，通过通配符匹配文件，忽略版本号
![image](https://github.com/lin2j/easy-deploy/assets/34084654/4a538cf9-a0da-4b35-add9-f4e8efc66831)

**2. 执行命令**
在执行命令处，可以自己指定参数，例如获取上传文件的名称，其中FILE_NAME为内置参数
![image](https://github.com/lin2j/easy-deploy/assets/34084654/f1091aa0-8eb5-4b8a-b5a3-054783428e75)

希望您能采纳我的建议，非常感谢

**Comment by gy0801151351** [comment]
能不能支持给每个 Command 配置添加一个标题? 每条updoad配置的Command多了之后, 容易不太记得哪条Command是干嘛的, 得点进去看Command详情了才清楚, 时间久了容易忘记. 如果能支持给每个Command配置一个标题就好了, 这样方便记忆.

**Comment by klaus-cicd** [comment]
你好，Alibaba Cloud Toolkit支持设置ssh代理，这个能不能支持一下
![image](https://github.com/lin2j/easy-deploy/assets/81892709/4b74dce0-b3c4-4c39-8caa-a8590ca29254)

**Comment by lin2j** [comment]
> 能不能支持给每个 Command 配置添加一个标题? 每条updoad配置的Command多了之后, 容易不太记得哪条Command是干嘛的, 得点进去看Command详情了才清楚, 时间久了容易忘记. 如果能支持给每个Command配置一个标题就好了, 这样方便记忆.

你好，功能已经实现，将在 [1.3.3 版本](https://github.com/lin2j/easy-deploy/releases/tag/v1.3.3)可以使用

**Comment by lin2j** [comment]
> 你好，Alibaba Cloud Toolkit支持设置ssh代理，这个能不能支持一下
> ![image](https://private-user-images.githubusercontent.com/81892709/325839145-4b74dce0-b3c4-4c39-8caa-a8590ca29254.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTM4MzYsIm5iZiI6MTcxNDMxMzUzNiwicGF0aCI6Ii84MTg5MjcwOS8zMjU4MzkxNDUtNGI3NGRjZTAtYjNjNC00YzM5LThjYWEtYTg1OTBjYTI5MjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE0MTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYzI4MGQyNzdiYWVlNzBmYjQzY2FiZWFiNzJiMmNlMjg0YjE2ZDJmYjA5MDI4MGM5NjlhYjRkZDBiMmM3ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XRjzq1G_MWTzEAGAqB7dcCzWKb6uUeOTiZRiSMXTg30)

可以的，我尽量在 1.3.4 版本做好这个功能。

**Comment by lin2j** [comment]
> 你好，Alibaba Cloud Toolkit支持设置ssh代理，这个能不能支持一下
> ![image](https://private-user-images.githubusercontent.com/81892709/325839145-4b74dce0-b3c4-4c39-8caa-a8590ca29254.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTg3MTEsIm5iZiI6MTcxNjIxODQxMSwicGF0aCI6Ii84MTg5MjcwOS8zMjU4MzkxNDUtNGI3NGRjZTAtYjNjNC00YzM5LThjYWEtYTg1OTBjYTI5MjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE1MjAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNjAxYzM5Zjk5MGY4YjFlY2U5ZDBlOTE5N2JhMjdjOTQ3ODJiMTRlNzg3MzVhODBjMjc4NjA2MmVhMmIxZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5F5IDzZ8z1vXX7AFMco5hxLdHQQ7eQn05-qioMnmIg8)

1.3.4 版本支持通过设置跳板机，以及给出当前配置的代理链路图
